server:
  port: 9999

spring:
  application:
    name: haha-iptables
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}